language: python

notifications:
  email:
    on_success: change
    on_failure: always

os:
- linux

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies

install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
- coverage run travis_tests.py


after_success:
- codecov

deploy:
  provider: pypi
  user: __token__
  skip_existing: true
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGIxNGMyZTY0LTMxNDQtNDI5Ny04MzAyLTNkOGU2ZWZhMmU2ZQACN3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJncHlvcHQiXX0sICJ2ZXJzaW9uIjogMX0AAAYg8hSEqfofZwxXHTcunWa_OArBqqdNWAfB50VRPPW_hQk
  on:
    branch: master
